# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Eric\Documents\GitHub\Team-Kakashi\LAA\resources\widget\Assignment4Widget\Widget.ui'
#
# Created: Wed Dec 02 18:27:40 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class PySideUiFileSetup(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(657, 515)
        Dialog.assignment4Label = QtGui.QLabel(Dialog)
        Dialog.assignment4Label.setGeometry(QtCore.QRect(30, 10, 111, 21))
        Dialog.assignment4Label.setObjectName("assignment4Label")
        Dialog.upBtn = QtGui.QPushButton(Dialog)
        Dialog.upBtn.setGeometry(QtCore.QRect(20, 40, 112, 34))
        Dialog.upBtn.setObjectName("upBtn")
        Dialog.downBtn = QtGui.QPushButton(Dialog)
        Dialog.downBtn.setGeometry(QtCore.QRect(20, 80, 112, 34))
        Dialog.downBtn.setObjectName("downBtn")
        Dialog.returnHomeBtn = QtGui.QPushButton(Dialog)
        Dialog.returnHomeBtn.setGeometry(QtCore.QRect(20, 120, 112, 34))
        Dialog.returnHomeBtn.setObjectName("returnHomeBtn")
        Dialog.schnauzUpBtn = QtGui.QPushButton(Dialog)
        Dialog.schnauzUpBtn.setGeometry(QtCore.QRect(170, 40, 131, 34))
        Dialog.schnauzUpBtn.setObjectName("schnauzUpBtn")
        Dialog.schnauzDownBtn = QtGui.QPushButton(Dialog)
        Dialog.schnauzDownBtn.setGeometry(QtCore.QRect(170, 80, 131, 34))
        Dialog.schnauzDownBtn.setObjectName("schnauzDownBtn")
        Dialog.eyebrowUpBtn = QtGui.QPushButton(Dialog)
        Dialog.eyebrowUpBtn.setGeometry(QtCore.QRect(350, 40, 131, 34))
        Dialog.eyebrowUpBtn.setObjectName("eyebrowUpBtn")
        Dialog.eyebrowDwnBtn = QtGui.QPushButton(Dialog)
        Dialog.eyebrowDwnBtn.setGeometry(QtCore.QRect(350, 80, 131, 34))
        Dialog.eyebrowDwnBtn.setObjectName("eyebrowDwnBtn")
        Dialog.smileSlider = QtGui.QSlider(Dialog)
        Dialog.smileSlider.setGeometry(QtCore.QRect(190, 210, 261, 22))
        Dialog.smileSlider.setMinimum(-10)
        Dialog.smileSlider.setMaximum(10)
        Dialog.smileSlider.setOrientation(QtCore.Qt.Horizontal)
        Dialog.smileSlider.setObjectName("smileSlider")
        Dialog.smileLabel = QtGui.QLabel(Dialog)
        Dialog.smileLabel.setGeometry(QtCore.QRect(60, 210, 91, 21))
        Dialog.smileLabel.setObjectName("smileLabel")
        Dialog.schnauzSlider = QtGui.QSlider(Dialog)
        Dialog.schnauzSlider.setGeometry(QtCore.QRect(189, 270, 261, 22))
        Dialog.schnauzSlider.setMinimum(-10)
        Dialog.schnauzSlider.setMaximum(10)
        Dialog.schnauzSlider.setOrientation(QtCore.Qt.Horizontal)
        Dialog.schnauzSlider.setObjectName("schnauzSlider")
        Dialog.noseLabel = QtGui.QLabel(Dialog)
        Dialog.noseLabel.setGeometry(QtCore.QRect(59, 270, 91, 21))
        Dialog.noseLabel.setObjectName("noseLabel")
        Dialog.eyebrowSlider = QtGui.QSlider(Dialog)
        Dialog.eyebrowSlider.setGeometry(QtCore.QRect(189, 330, 261, 22))
        Dialog.eyebrowSlider.setMinimum(-10)
        Dialog.eyebrowSlider.setMaximum(10)
        Dialog.eyebrowSlider.setOrientation(QtCore.Qt.Horizontal)
        Dialog.eyebrowSlider.setObjectName("eyebrowSlider")
        Dialog.eyebrowLabl = QtGui.QLabel(Dialog)
        Dialog.eyebrowLabl.setGeometry(QtCore.QRect(40, 330, 121, 21))
        Dialog.eyebrowLabl.setObjectName("eyebrowLabl")
        Dialog.widenSlider = QtGui.QSlider(Dialog)
        Dialog.widenSlider.setGeometry(QtCore.QRect(189, 390, 261, 22))
        Dialog.widenSlider.setMinimum(0)
        Dialog.widenSlider.setMaximum(2)
        Dialog.widenSlider.setOrientation(QtCore.Qt.Horizontal)
        Dialog.widenSlider.setObjectName("widenSlider")
        Dialog.headLabel = QtGui.QLabel(Dialog)
        Dialog.headLabel.setGeometry(QtCore.QRect(60, 390, 91, 21))
        Dialog.headLabel.setObjectName("headLabel")
        Dialog.lengthSlider = QtGui.QSlider(Dialog)
        Dialog.lengthSlider.setGeometry(QtCore.QRect(190, 450, 261, 22))
        Dialog.lengthSlider.setMinimum(0)
        Dialog.lengthSlider.setMaximum(2)
        Dialog.lengthSlider.setOrientation(QtCore.Qt.Horizontal)
        Dialog.lengthSlider.setObjectName("lengthSlider")
        Dialog.label = QtGui.QLabel(Dialog)
        Dialog.label.setGeometry(QtCore.QRect(40, 450, 121, 21))
        Dialog.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.assignment4Label.setText(QtGui.QApplication.translate("Dialog", "Assignment 4", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.upBtn.setText(QtGui.QApplication.translate("Dialog", "Smile Up", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.downBtn.setText(QtGui.QApplication.translate("Dialog", "Smile Down", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.returnHomeBtn.setText(QtGui.QApplication.translate("Dialog", "Return Home", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.schnauzUpBtn.setText(QtGui.QApplication.translate("Dialog", "Nose Up", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.schnauzDownBtn.setText(QtGui.QApplication.translate("Dialog", "Nose Down", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.eyebrowUpBtn.setText(QtGui.QApplication.translate("Dialog", "Eyebrows Up", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.eyebrowDwnBtn.setText(QtGui.QApplication.translate("Dialog", "Eyebrows Down", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.smileLabel.setText(QtGui.QApplication.translate("Dialog", "Smile Slider", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.noseLabel.setText(QtGui.QApplication.translate("Dialog", "Nose Slider", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.eyebrowLabl.setText(QtGui.QApplication.translate("Dialog", "Eyebrow Slider", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.headLabel.setText(QtGui.QApplication.translate("Dialog", "Widen Head", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.label.setText(QtGui.QApplication.translate("Dialog", "Lengthen Head", None, QtGui.QApplication.UnicodeUTF8))

